version: '2'
services:
  mysql:
    build: ./mysql/. 
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
